;task 1


.386
.model flat,stdcall
.stack 4096
ExitProcess proto,dwExitCode:dword

.data

.code

main PROC
	mov al,00110101b	;store 00110101b in al
	mov bl,01011100b	;store 01011100b in bl
	add al,bl	;add and store in al i.e 145

	INVOKE exitProcess,0
main ENDP
END main